spring.application.name=shop
server.port=9090
#logging.level.root=DEBUG
 
spring.datasource.url = jdbc:mysql://localhost:3306/onlinebookshop
spring.datasource.username = root
spring.datasource.password = Genpact@123456789
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver


# Enable SQL Script for Table Creation - enables sql scripts
#spring.sql.init.mode = ALWAYS
# Show SQL Queries in Console
spring.jpa.show-sql = true
# SQL initialization platform - specifies that database is mysql
spring.sql.init.platform = mysql

spring.wed.cors.allowed.origins=https://localhost:3002
spring.wed.cors.allowed-methods=GET ,POST ,PUT ,DELETE
spring.wed.cors.allowed-headers=*
spring.wed.cros.allowed-credentials=true


#spring.application.name=shop
#server.port=9090
## Data source configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/onlinebookshop
#spring.datasource.username=root
#spring.datasource.password=Genpact@123456789
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
## enable sql script for table creation 
# spring.sql.intit.mode=ALWAYS
# #show sql queries in console
# spring.jpa.show-sql=true
# #sql initialization platform
# spring.sql.intit.platform=mysql

