CREATE TABLE authors(
   id INT AUTO_INCREMENT PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   country VARCHAR(255) NOT NULL
);

CREATE TABLE books(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  price DECIMAL(10,2),
  authorId INT NOT NULL,
  FOREIGN KEY (authorId) REFERENCES authors(id) ON DELETE CASCADE
);
CREATE TABLE orders(
id INT AUTO_INCREMENT PRIMARY KEY,
bookId INT NOT NULL,
quantity INT NOT NULL,
orderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (bookId) REFERENCES books(id) ON DELETE CASCADE
);
